In [1]:
import pandas as pd

In [2]:
import numpy as np

## Array

In [4]:
my_array = np.array([1,2,3])
print(my_array)

[1 2 3]


* accessing an array

In [5]:
my_array[0]

1

* two values in an array

In [6]:
my_2d_array = np.array([[1,2,3],[4,5,6]])
print(my_2d_array)

[[1 2 3]
 [4 5 6]]


In [7]:
my_2d_array[1,1]

5

In [8]:
my_2d_array[0,0]

1

In [9]:
my_2d_array[0,2]

3

## Creat Dataframe

In [18]:
instructors_data = {
    "name": ["Del","Aileen","Mhairi","Steph","Mandy","Colin"],
    "favourite_number": [7,12,3,9,4,11]
}
instructors_data

{'name': ['Del', 'Aileen', 'Mhairi', 'Steph', 'Mandy', 'Colin'],
 'favourite_number': [7, 12, 3, 9, 4, 11]}

In [12]:
type(instructors_data)

dict

In [19]:
instructors_dataframe = pd.DataFrame(instructors_data)

instructors_dataframe 

name  favourite_number
0     Del                 7
1  Aileen                12
2  Mhairi                 3
3   Steph                 9
4   Mandy                 4
5   Colin                11

In [21]:
instructors_dataframe = pd.DataFrame({
    "name": ["Del", "Aileen", "Mhairi", "Steph", "Mandy", "Colin"],
    "favourite_number": [7, 12, 3, 9, 4,11] 
})
instructors_dataframe

name  favourite_number
0     Del                 7
1  Aileen                12
2  Mhairi                 3
3   Steph                 9
4   Mandy                 4
5   Colin                11

* Add index

In [33]:
instructors_dataframe = pd.DataFrame({
    "name": ["Del", "Aileen", "Mhairi", "Steph", "Mandy", "Colin"],
    "favourite_number": [7, 12, 3, 9, 4,11]},
    index = range(1,7))
instructors_dataframe

name  favourite_number
1     Del                 7
2  Aileen                12
3  Mhairi                 3
4   Steph                 9
5   Mandy                 4
6   Colin                11